### Pridobi vse dogodke
GET http://localhost:5000/api/events

###

### Dodaj dogodek
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "title": "EventEase test",
  "description": "Testni opis dogodka",
  "dateTime": "2025-06-03T18:00:00",
  "location": "Ljubljana",
  "imageUrl": "",
  "allowSignup": true,
  "ownerId": "auth0|nekaj"
}

###

### Prijava na dogodek
POST http://localhost:5000/api/signups/aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1
Content-Type: application/json

{
  "userId": "auth0|nekaj"
}
